'use strict';

const SUCCESSFUl = 200;
const CREATED = 201;
const DELETED = 204;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const UNPROCESSABLE_ENTITY = 422;

export default {
  SUCCESSFUl,
  CREATED,
  DELETED,
  BAD_REQUEST,
  NOT_FOUND,
  UNPROCESSABLE_ENTITY,
};
